#!/usr/bin/env php
<?php
ini_set('memory_limit', '1024M');

function print_array($arr)
{
	echo "{ ";
	foreach ($arr as $k=>$v) 
	{
		echo $v . " "; 
	}
	echo "}";
}

function get_pivot1($s, &$graph)
{
	$i = 0; $n = 0;
	
	foreach ($s as $k=>$v) 
	{
		if (count($graph[$v]) > $n)
		{
			$n = count($graph[$v]);
			$i = $v;
		}
	}
	
	return $i;
}

function get_pivot2($s)
{
	reset($s);
	$u = current($s);
	
	return $u;
}

function bron_kerbosch1($r, $p, $x, &$graph, &$cliques)
{
	if ((count($p) == 0) && (count($x) == 0))
	{
//		echo "Maximal clique:";
//		print_r($r);
        if (count($r) > 2)
        {
            $cliques[] = $r;
        }
		return; 
	}
	foreach ($p as $v) 
	{
		bron_kerbosch1
		(
			array_merge($r, array($v)), 
			array_intersect($p, $graph[$v]),
			array_intersect($x, $graph[$v]),
			$graph, 
			$cliques
		);
		$p = array_diff($p, array($v));
		$x = array_merge($x, array($v)); 
	}
}

function bron_kerbosch2($r, $p, $x, &$graph, &$cliques)
{
/*
	for ($i = 0; $i < $depth; $i++) 
		echo "  ";
	echo "bron_kerbosch2\n";
*/
    
//	echo "bron_kerbosch2(";
//	print_array($r);
//	echo ", ";
//	print_array($p);
//	echo ", ";
//	print_array($x);
//	echo ")\n";
	
	if ((count($p) == 0) && (count($x) == 0))
	{
		//echo "Maximal clique:";
		//print_r($r);
        if (count($r) > 2)
        {
            $cliques[] = $r;
        }
		return;
	}
	
    $u = get_pivot1(array_merge($p, $x), $graph);
		
//	echo "u: $u\n";
	if (empty($u))
		return;
	
	$pv = array_diff($p, $graph[$u]);
	
	foreach ($pv as $v) 
	{
		bron_kerbosch2
		(
			array_merge($r, array($v)), 
			array_intersect($p, $graph[$v]),
			array_intersect($x, $graph[$v]),
			$graph,
            $cliques
		);
		$p = array_diff($p, array($v));
		$x = array_merge($x, array($v)); 
	}
}

$graph = array();
$cliques = array();
$handle = fopen($argv[1], "r");

while (($line = fgets($handle)) !== false) 
{
    $line = trim($line);
    $vals = explode("\t", $line);
/*
    var_dump($vals);
*/
    if ($vals[1] != $vals[2]) 
    {
        if (!array_key_exists($vals[1], $graph))
        {
            $graph[$vals[1]] = array();
        }
        
        if (!in_array($vals[2], $graph[$vals[1]]))
        {
            $graph[$vals[1]][] = $vals[2];
        }
    }
}
fclose($handle);

/*
foreach ($graph as $vertex => $neighbours)
{
    foreach ($neighbours as $key => $neighbour)
    {
        if (!in_array($vertex, $graph[$neighbour]))
        {
            
        }
    }
}
*/

//var_dump($graph);

//bron_kerbosch1(array(), array_keys($graph), array(), $graph, $cliques);
bron_kerbosch2(array(), array_keys($graph), array(), $graph, $cliques);

foreach ($cliques as &$clique)
{
    sort($clique, SORT_STRING);
    echo implode(", ", $clique) . "\n";
}
//var_dump($cliques);

